### ISSUE TITLE
Ember link is 404 'UnrecognizedURLError'

### ISSUE THREAD

**Issue by sheriffderek** [tastejs/todomvc#1743] opened 2017-01-12 02:25 UTC
I wanted to check out the Ember todoApp and I noticed that the Ember link is 404 'UnrecognizedURLError.'

http://todomvc.com/examples/emberjs/index.html/examples/emberjs/

I checked all of the other links, and they all seem Aok.

**Comment by passy** [comment] 2017-01-15 15:19
Dupe of #1650.

**Closed by passy** 2017-01-15 15:19 UTC
