### ISSUE TITLE
Clear completed button not clickable in Firefox

### ISSUE THREAD

**Issue by blakehaswell** [tastejs/todomvc#1252] opened 2015-04-06 11:04 UTC
To reproduce:

* Open http://todomvc.com/examples/backbone/ in Firefox
* Add an item
* Mark it as complete
* Click “clear completed”

Appears to be a z-index issue, `ul#filters` seems to be displaying above the clear completed button.

**Comment by gnjec** [comment] 2015-04-07 12:32
here is the solution:

#clear-completed,
html #clear-completed:active {
	float: right;
	position: relative;
	line-height: 20px;
	text-decoration: none;
	cursor: pointer;
	//visibility: hidden;
	position: relative;
}

#clear-completed::after {
	visibility: visible;
	//content: 'Clear completed';
	position: absolute;
	right: 0;
	white-space: nowrap;
}

**Comment by gnjec** [comment] 2015-04-07 12:48
in chrome and in firefox etc... 
there should be: Clear completed (2) - exemple
and there is only: Clear completed - inserted via css content (::after)
- visibility for html template is hidden and only css content is rendered -

but it has to be done in all exemples

**Comment by samccone** [comment] 2015-04-07 13:13
I think this should be fixed when we bump the version of the app css.. will do now

**Comment by gnjec** [comment] 2015-04-07 14:19
The issue is same for all examples (I think, just checked angularjs and emberjs).

**Comment by arthurvr** [comment] 2015-04-07 14:21
Updating the todomvc-app-css version will anyways happen soon as part of https://github.com/tastejs/todomvc/issues/1234.

**Comment by samccone** [comment] 2015-04-07 14:21
yep yep

**Comment by samccone** [comment] 2015-04-07 15:04
Will be fixed when #1234 lands

**Comment by blakehaswell** [comment] 2015-04-07 19:03
Sweet. :+1:

**Comment by arthurvr** [comment] 2015-04-07 19:05
I've been granting that PR priority today. Hopefully able to land realllyyyyy soon.

**Comment by samccone** [comment] 2015-04-22 17:47
@arthurvr I think we can close this now :)

**Closed** 2015-04-22 17:49 UTC
