### ISSUE TITLE
Meteor link broken

### ISSUE THREAD

**Issue by badraufran** [tastejs/todomvc#1611] opened 2016-04-06 23:09 UTC
The link to the Meteor example is broken. [http://todomvcapp.meteor.com/](http://todomvcapp.meteor.com/) doesn't exist.

**Comment by arthurvr** [comment] 2016-11-06 16:01
Thanks for the report! I'm gonna close this as it's a duplicate of #1617 :)

**Closed by arthurvr** 2016-11-06 16:01 UTC
