### ISSUE TITLE
Ember example blank

### ISSUE THREAD

**Issue by jernejc** [tastejs/todomvc#1708] opened 2016-10-19 18:17 UTC
Hi,

the ember.js example loads blank:
http://todomvc.com/examples/emberjs/index.html/examples/emberjs/

**Comment by Otolock** [comment] 2016-10-25 14:31
It looks like the link is bad. If you erase the extra `/examples/emberjs/`, it loads the app correctly.

**Comment by jernejc** [comment] 2016-10-25 14:52
Ok, seems like it was fixed. 
That's the link I was being redirected to if visiting: 
http://todomvc.com/examples/emberjs/index.html

Thanks

**Comment by Otolock** [comment] 2016-10-25 14:58
The app is working, but the redirect on the main page is acting weird for Ember.

**Comment by arthurvr** [comment] 2016-11-06 15:28
Hm, strange. Closing this as a duplicate of https://github.com/tastejs/todomvc/issues/1695 though.

**Closed by arthurvr** 2016-11-06 15:28 UTC

**Comment by ciroreed** [comment] 2016-12-13 15:14
Here -> http://todomvc.com/ Ember url is broken or something.. it goes to http://todomvc.com/examples/emberjs which is still broken
