### ISSUE TITLE
Example Wanted: Reagent

### ISSUE THREAD

**Issue by passy** [tastejs/todomvc#1053] opened 2014-10-29 13:08 UTC
There's another ClojureScript library based on the Virtual DOM model called Reagent that is often compared to Om. It would be great to have an example here so you can directly compare the two.

A TodoMVC implementation is available here: https://github.com/holmsand/reagent/tree/master/examples/todomvc

**Comment by arthurvr** [comment] 2015-03-21 12:57
Duplicate of #985.

**Closed by arthurvr** 2015-03-21 12:58 UTC
Labels: wishlist
