### ISSUE TITLE
Express + gcloud-node not working 

### ISSUE THREAD

**Issue by shridharkalagi** [tastejs/todomvc#1978] opened 2019-06-26 12:46 UTC
Seeing the below error
![image](https://user-images.githubusercontent.com/18380219/60180796-7338b000-983e-11e9-936a-14a61fe24a37.png)

**Comment by AdityaGupta150** [comment] 2020-08-14 11:31
Duplicate of #1797 

Though not that, they might have seen this 🤔

**Closed** 2020-10-08 23:52 UTC
