### ISSUE TITLE
Implementation inconsistencies seem to mislead public bloggers

### ISSUE THREAD

**Issue by dmitriz** [tastejs/todomvc#1575] opened 2016-01-05 05:46 UTC
[A recent high profile blog](https://medium.com/@housecor/angular-2-versus-react-there-will-be-blood-66595faafd51#.6yd8v3oze) with 700+ likes and 70+ comments is showing this comparison:

>Ember: 580k
Angular 2: 565k (759k with RxJS)
React + Redux: 204k
Angular 1: 145k <-Edit — Had wrong size earlier.

(Angular 1 revised down after I [wrote to the author](https://medium.com/@dmitri145/angular-1-4-8-min-js-is-actually-only-148k-6342b941c9a3#.ieamoacvf).)

Then [I discovered](https://medium.com/@housecor/where-are-you-getting-those-numbers-f76a298ceab#.ctrn11y81), [where these numbers come from](https://aerotwist.com/blog/the-cost-of-frameworks/), which happens to be based on this project, hence the reason for this Issue here.

As appears, the tests there were based on the examples from http://todomvc.com/. Upon inspection, it appears that [the official AngularJS example](http://todomvc.com/examples/angularjs/) is [loading the almost 1MB heavy unminified source](https://github.com/tastejs/todomvc/blob/master/examples/angularjs/index.html#L67), whereas e.g. [the Polymer example](http://todomvc.com/examples/polymer/index.html) is [loading the much smaller `webcomponents-lite.min.js` of only 39k](https://github.com/tastejs/todomvc/blob/master/examples/polymer/index.html#L37)

Whence the drastic difference in the given test results for the two libraries!

I know that performance comparison was not the point of this project but it seems that's how people use it now, unfortunately. :(

**Comment by addyosmani** [comment] 2016-01-05 10:08
https://github.com/tastejs/todomvc/issues/1541 will address this. I think we should power ahead with enabling this as an option with some of the more often referenced examples.

**Comment by passy** [comment] 2016-01-06 20:49
Another one Sam found earlier today: https://docs.google.com/document/d/1eDnJ-NpJBjicxVkrZgCwMHewSZUUePVY6LCVPS_swAw/pub

TodoMVC payload sizes and "execution performance" metrics are used here for evaluating the best framework fit.

While it's extremely unfortunate that people use the current state of the project to (mis)inform their decisions, it's also a strong indicator that there is demand for exactly this: baseline framework overhead and startup/runtime performance metrics for a small apps. So :+1: for getting #1541 ready.

**Comment by samccone** [comment] 2016-01-06 21:13
going to close this issue as being essentially a duplicate of #1541

**Closed by samccone** 2016-01-06 21:13 UTC

**Comment by dmitriz** [comment] 2016-01-07 02:58
It is interesting how in that comparison React is named more "mature" than Ember, where I think the opposite is true.

**Comment by passy** [comment] 2016-01-07 07:40
I don't think we're anywhere close to being able to quantify framework
maturity. :)

**Comment by dmitriz** [comment] 2016-01-07 08:53
Not even the people listed underneath?

>Special thanks to the following experts who provided review and input:
Miško Hevery (creator of Angular; Google)
Igor Minar (technical lead for Angular; Google)
Ed Faulkner (core maintainer for Ember)
Amitai Burstein (Drupal and Elm contributor; Gizra)
Sebastian Siemssen (Drupal contributor, Elm and React developer; Zensations)
John Albin Wilkins (Drupal 8 mobile initiative lead)
Alex Bronstein (Drupal core maintainer; Acquia)
Wim Leers (Drupal core contributor; Acquia)
Dries Buytaert (Drupal project lead; Acquia)
Preston So (Drupal contributor; Acquia)

**Comment by samccone** [comment] 2016-01-07 16:42
I can't imagine that there was no bias ^ ;)
