### ISSUE TITLE
Remove labs

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/todomvc#811] opened 2014-02-02 02:04 UTC
Let's try to get all apps spec compliant and remove some unwanted ones (that aren't used/maintained).

The distinction has been a source of confusion and sometimes annoyment without giving a lot of benefit.

This is easier now that we have actual testing.

Let's do it before the 1.3 release.

**Comment by arthurvr** [comment] 2015-03-13 20:33
Duplicate of #845.

**Closed by arthurvr** 2015-03-13 20:33 UTC
Labels: discussion, site
