### ISSUE TITLE
Backbone Example is not working

### ISSUE THREAD

**Issue by harshal-avantsoft** [tastejs/todomvc#1307] opened 2015-05-21 15:29 UTC
I copied all the files into my machine then try to run the app is not able to load and found the error below is the screenshot for that....

![screen shot 2015-05-21 at 8 58 31 pm](https://cloud.githubusercontent.com/assets/2596437/7752282/328811ba-fffc-11e4-9a09-cd1af5134903.png)

**Comment by arthurvr** [comment] 2015-05-21 15:32
This seems like something which went wrong while downloading the example. It isn't reproducible on the live site. Ideal is to clone just clone the `todomvc` repo and run a local server.

**Comment by samccone** [comment] 2015-05-21 15:38
closing since this is not reproducible via a clone of the repo

**Closed by samccone** 2015-05-21 15:38 UTC

**Comment by harshal-avantsoft** [comment] 2015-05-21 15:45
I just want backbone example, will it be possible to run the app without support of

node_modules/todomvc-common/base.js

**Comment by harshal-avantsoft** [comment] 2015-05-21 15:46
I just copy pasted the files in other directory and it's not working for me...do I need to configure anything else...

**Comment by harshal-avantsoft** [comment] 2015-05-21 15:47
this is my repository >>> https://github.com/harshal-avantsoft/JSExplore
