### ISSUE TITLE
Firefox check icon is incorrect

### ISSUE THREAD

**Issue by samccone** [tastejs/todomvc#1259] opened 2015-04-07 22:34 UTC
##### Firefox

![](http://dl.dropbox.com/u/36928599/Screenshots/0p8.png)
##### Chrome

![](http://dl.dropbox.com/u/36928599/Screenshots/0p9.png)

**Comment by gnjec** [comment] 2015-04-17 19:56
In Firefox, css ```:after``` and ```:before``` not working on form elements (inputs - checkboxes).

**Comment by arthurvr** [comment] 2015-05-10 12:30
@samccone Can you reopen this issue in todomvc-app-css? That's where the actual CSS lives so it deserves there, right?

**Comment by urrgur** [comment] 2015-05-26 06:49
ping samcone

**Comment by samccone** [comment] 2015-05-26 12:36
You are correct not directly. It is related to the css repo and an issue should also be filed there. However many people open issues on the repo around this issue and I wanted to make sure we track it in both places since this repo makes the bug visible.

**Comment by sindresorhus** [comment] 2015-05-26 12:47
I'm not sure there's anything we can do about this. As mentioned earlier in this thread it's a Firefox bug.

**Comment by arthurvr** [comment] 2015-05-26 16:09
> However many people open issues on the repo around this issue and I wanted to make sure we track it in both places since this repo makes the bug visible.

In fact I think we should move it and add a note about those repos (both app-css and todomvc-common) in `contributing.md`.

**Comment by samccone** [comment] 2015-07-13 01:11
Do we have any bugtracker link for this upstream in firefox?

**Comment by arthurvr** [comment] 2015-08-22 18:12
Isn't this a dupe of https://github.com/tastejs/todomvc/issues/1408?

**Comment by samccone** [comment] 2015-08-22 18:56
they will all be closed very soon once we land the fix from @patrickkettner

**Comment by Fruitseller** [comment] 2018-06-23 19:45
Can this issue be closed? The PR mentioned by @samccone was merged on Mar 20, 2017.

I can't see the screenshots initialy posted but in my local testing the check icons looked good.(tested on Firefox 60)
On http://todomvc.com they look broken(no styling) but I'm not sure which version is deployed.

**Comment by FadySamirSadek** [comment] 2018-06-24 00:46
@Fruitseller  You are right the fix has not been deployed yet but this should have been closed. Thank you 👍

**Closed by FadySamirSadek** 2018-06-24 00:46 UTC
