### ISSUE TITLE
blog.tastejs.com redirects to ghost.org

### ISSUE THREAD

**Issue by augbog** [tastejs/todomvc#1387] opened 2015-07-25 05:05 UTC
Is the blog supposed to redirect to ghost.org homepage? Feel free to close if this is not an issue.

**Comment by arthurvr** [comment] 2015-07-25 09:56
We're aware. Sorry :cry: 

Closing as a dupe of https://github.com/tastejs/todomvc/issues/1217.

**Closed by arthurvr** 2015-07-25 09:56 UTC
