### ISSUE TITLE
Angular + Typescript 

### ISSUE THREAD

**Issue by ToddThomson** [tastejs/todomvc#1452] opened 2015-10-01 00:01 UTC
The sample using Angular 1.4.7 and Typescript 1.6.2 does not properly list the todo items when the list is shown with the ALL filter selected.

**Comment by samccone** [comment] 2015-10-01 00:07
It seems to be working for me,

![screen shot 2015-09-30 at 5 06 37 pm](https://cloud.githubusercontent.com/assets/883126/10209913/a46b6434-6795-11e5-8819-2afc701a22ed.png)

@ToddThomson mind listing the steps to reproduce the bug? thanks!!

**Comment by ToddThomson** [comment] 2015-10-01 14:10
@samccone Yes, running the typescript-angular example from the todomvc.com site or downloading and running from a vs2015 website project works as above ( without doing a build first ). The version of angular that is downloaded is 1.3.13.
When updating angular to 1.4.7 with npm install, the sample no longer works properly. When the "All" filter is selected, items may still be added, but they are not listed. When the "Active" filter is selected, the todo items are shown.

**Comment by ToddThomson** [comment] 2015-10-01 14:20
@samccone Note that I did not do a compile of the typescript files. Angular.js 1.3.13 to 1.4.7 breaks the working demo. Back to Angular 1.3.13 and the demo works.

**Comment by ToddThomson** [comment] 2015-10-01 19:29
OK, I've got everything working with the angular bower_module set to 1.3.13. This is fine for my purposes.
If you are interested, I've build a version of todoMVC using Typescript, Angular and Require using a gulp adaptor (TsProject) I built to bundle typescript es6 modules.

**Comment by samccone** [comment] 2015-10-01 19:50
Hey @ToddThomson so things breaking between 1.3 and 1.4 is no so suprising since there were significant breaking changes between those releases of angular.

Are you interested in updating the example to 1.4.x?

---

I am going to close this issue since this is not exactly an issue with our code

**Closed by samccone** 2015-10-01 19:50 UTC

**Comment by ToddThomson** [comment] 2015-10-01 20:13
@samccone Sure, I have this afternoon to work on OSS. Here is the link to the TsProjectTodoMVC github repository if you are interested: TsProject (https://github.com/ToddThomson/tsproject)
I'm working on the readme docs right now and I will link back to your TodoMVC.

**Comment by ToddThomson** [comment] 2015-10-02 18:43
@samccone Sorry, I don't have the time to issue a PR. To fix the todoMVC typescript + angular app you need to modify TodoCtrl.ts. This will allow the example to run with Angular 1.4.7.
```
onPath(path: string) {
	this.$scope.statusFilter = (path === '/active') ?
		{ completed: false } : (path === '/completed') ?
		{ completed: true } : undefined; // CHANGE HERE - was null
}
```

**Comment by samccone** [comment] 2015-10-02 18:44
great thanks for the patch @ToddThomson :sparkles:

**Comment by ToddThomson** [comment] 2015-10-02 19:02
@samccone I forgot one other issue when using the 1.4+ Angular typescript definition file ( and using the Typescript 1.6.2 compiler ). You need to change the following line to ( it requires a typecast to any to get past the compilation error ):

    $scope.$watch( 'location.path()', path => this.onPath( path as any ) );
