### ISSUE TITLE
FOAM example's "Clear completed" link doesn't work in Firefox 

### ISSUE THREAD

**Issue by drbraden** [tastejs/todomvc#1286] opened 2015-05-03 06:15 UTC
Didn't work for me using Firefox 37.0.2 on OS X 10.10.3.  Checked using Chrome and Safari and worked fine.

http://todomvc.com/examples/foam/

**Comment by arthurvr** [comment] 2015-05-03 08:16
Duplicate of https://github.com/tastejs/todomvc/issues/1252, FOAM [is one of the only ones](https://github.com/tastejs/todomvc/issues/1234) that still needs fixing.

**Closed by arthurvr** 2015-05-03 08:16 UTC
