### ISSUE TITLE
EmberJS TodoMVC Broken

### ISSUE THREAD

**Issue by SIRHAMY** [tastejs/todomvc#1695] opened 2016-09-29 19:55 UTC
The link from the main pages directs to: http://todomvc.com/examples/emberjs/index.html/examples/emberjs/

The URL returns a 404 not found error.

**Comment by Luiz-N** [comment] 2016-10-02 22:09
The working url is:
[http://todomvc.com/examples/emberjs/index.html](http://todomvc.com/examples/emberjs/index.html)
It's probably just some sort of re-direct bug.

**Comment by arthurvr** [comment] 2016-11-06 15:32
Hm, indeed, strange. I guess something's going on in its router. I don't really have time to investigate this myself atm though, so PRs welcome 😆  The ember apps needs some serious cleanup regarding some other stuff too btw :/

**Comment by arthurvr** [comment] 2016-11-06 15:40
Oh, this is a duplicate of https://github.com/tastejs/todomvc/issues/1650, sorry :)

**Closed by arthurvr** 2016-11-06 15:40 UTC
