### ISSUE TITLE
TypeScript + Backbone: TypeError on Windows 10 (Chrome, Firefox, Edge, IE 11)

### ISSUE THREAD

**Issue by maurocastagnetti** [tastejs/todomvc#1402] opened 2015-08-09 22:33 UTC
In the previous week i have installed windows 10, the typescript+backbone version do not work anymore, 
if you try to create a new item and then press the return  key the javascript console show the following error:
"app.js:105 Uncaught TypeError: Cannot read property 'get' of undefined".

Below the corresponding piece of code
...
// We keep the Todos in sequential order, despite being saved by unordered
    // GUID in the database. This generates the next order number for new items.
    TodoList.prototype.nextOrder = function () {
        if (!length)
            return 1;
        return this.last().get('order') + 1;
    };
...

The error occurs in:

Chrome 44.0.2403.130 m
Firefox 39.0.3
Microsoft Edge browser 20.10240.16384.0
Internet explorer 11

I belive that is something related with windows 10 because 
1) the error is the same on different browser
2) on another pc with windows 7 and the same version of chrome the error doesn't occur.
3) on mac os x and the same version of chrome again the error doesn't occur

Regards
Mauro.

**Comment by samccone** [comment] 2015-08-11 21:14
@maurocastagnetti any interest in investigating / fixing?

**Comment by passy** [comment] 2015-08-12 13:23
Couldn't reproduce with Edge. It isn't particularly pretty, but functional.

![screenshot 2015-08-12 14 22 39](https://cloud.githubusercontent.com/assets/9906/9224879/a726905e-40fd-11e5-99f6-2364d7905358.png)

**Comment by samccone** [comment] 2015-08-12 13:25
hahaha those checkmarks are on point

**Comment by passy** [comment] 2015-08-12 13:27
The top one is like

![you-cant-handle-my-fabulousness-1362095093](https://cloud.githubusercontent.com/assets/9906/9224964/45465da0-40fe-11e5-80ea-f6809215c7c5.jpg)

**Comment by samccone** [comment] 2015-08-12 13:36
alright going to close this one, unless someone else can reproduce and then we can reopen.

**Closed by samccone** 2015-08-12 13:36 UTC
Labels: bug
